include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    # prefer_expression_function_bodies: true
    prefer_relative_imports: true
    # always_specify_types: true
    curly_braces_in_flow_control_structures: true
    lines_longer_than_80_chars: false

    avoid_print: true
    avoid_catching_errors: true
    avoid_returning_null_for_void: true
    no_duplicate_case_values: true
    unawaited_futures: true

    # package_api_docs: true
    # public_member_api_docs: true
    sort_constructors_first: true
    sort_child_properties_last: true
